name: "Pull Request Labeler"
on: [pull_request_target]
permissions:
  contents: read
jobs:
  triage:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
